//
//  CCHierarchiesSpriteConfig.h
//  CCHierarchiesSprite
//
//  Created by Xu Xiaocheng <xcxu@bread-media.com.cn>.
//  Copyright (c) 2012 Break-media. All rights reserved.
//

#ifndef _CCHierarchiesSpriteConfig_H_
#define _CCHierarchiesSpriteConfig_H_

#include "cocos-ext.h"

#define HIERARCHIES_SPRITE_ENABLE_AVATER 1
#define HIERARCHIES_SPRITE_ENABLE_DYEING 1
#define HIERARCHIES_SPRITE_ENABLE_EVENT_IN_ANIMATION 1
#define HIERARCHIES_SPRITE_CACHE_SPRITE_SHEET 1
#define HIERARCHIES_SPRITE_CACHE_ANIMATION 1
#define HIERARCHIES_SPRITE_ALWAY_CACHE_SPRITE_SHEET 0
#define HIERARCHIES_SPRITE_ALWAY_CACHE_ANIMATION 0
#define HIERARCHIES_SPRITE_CACHE_RUNTIME_ANIMATION 1
//#define HIERARCHIES_SPRITE_MULTI_THREAD_ANIMATION_IN_BATCH 1
//#define HIERARCHIES_SPRITE_2X 0
#define HIERARCHIES_SPRITE_ONE_ELEMENT_IN_ONE_FRAME 0
#define HIERARCHIES_SPRITE_PROFILER 1
//#define HIERARCHIES_SPRITE_BATCH_NODE_PROFILER 0
//#define HIERARCHIES_SPRITE_CLEAR_DEPTH_BUFFER_BETWEEN_DRAW 1
#define HIERARCHIES_DEBUG_DRAW 0

#define HIERARCHIES_SPRITE_DEFAULT_TEXTURE_ATLAS_CAPACITY (40)
//#define HIERARCHIES_SPRITE_BATCH_NODE_DEFAULT_TEXTURE_ATLAS_CAPACITY (1000)
//#define HIERARCHIES_SPRITE_BATCH_Z_ORDER_SCALE (0.1f)
#define HIERARCHIES_SPRITE_LAYER_Z_ORDER_SCALE (0)

#define HIERARCHIES_SPRITE_AVATAR_TAG_SEPARATOR ('/')
//#define HIERARCHIES_SPRITE_AVATAR_TAG_SEPARATOR_NSSTRING (@"/")
#define HIERARCHIES_SPRITE_AVATAR_TAG_SEPARATOR_STRING ("/")

#endif
